all: read_write.out write.out print_argv.out write_stop.out sleep.out exit.out print_env.out

read_write.out: read_write.c
	gcc read_write.c -o read_write.out

write.out: write.c
	gcc write.c -o write.out

print_argv.out: print_argv.c
	gcc print_argv.c -o print_argv.out

write_stop.out: write_stop.c
	gcc write_stop.c -o write_stop.out

sleep.out: sleep.c
	gcc sleep.c -o sleep.out

exit.out: exit.c
	gcc exit.c -o exit.out

print_env.out: print_env.c
	gcc print_env.c -o print_env.out
