all: read_write.out write.out print_argv.out

read_write: read_write.c
	gcc read_write.c -o read_write.out

write: write.c
	gcc write.c -o write.out

print_argv: print_argv.c
	gcc print_argv.c -o print_argv.out

